### ISSUE TITLE
How to access my current working directory?

### ISSUE THREAD

**Issue by DrCWO** [megastep/makeself#251]
My opinion: makeself is really a GEAT tool. Thank you so for making it.

My use case is packing a tree of node.js files in one archive and starting "node index.js".
I copied the packed archive "myApp" in /usr/local/bin

Would you please tell me how to get the path of my current working directory "home/mywork" within my application when I start myApp from within "home/mywork"?

I always get the path to a /tmp/... anything.

Thank you

**Comment by megastep** [comment]
The makeself archive is always extracted in a temporary location (usually under `/tmp`) and that's why you get that as your current directory. If you want to extract it explicitly at some other location, you can use the `--target` argument to give it a path.

Makeself is *not* meant to use as an application package like a regular application binary. There are serious security issues surrounding this kind of usage and I suggest you find a better way to do this...
