### ISSUE TITLE
Cannot execute .run file on OVA

### ISSUE THREAD

**Issue by dorothyzz** [megastep/makeself#276]
Hi, 
I'm installing packages' updates with makeself file and cannot execute .run file on the OVA machine. This is the error I get:
`./third_party_packages_latest.run: 1: eval: ./post_unpack.sh: Permission denied`
The post_unpack.sh is executable, the error reproduces itself with permission escalation, re-created the makeself file locally with the same error while running it.
When running this file on another machine, the installation is successful. I unpacked the .run file and executed the bash script locally without errors. What can cause this problem??
Thanks in advance!

**Comment by megastep** [comment]
Hi there,

I've noticed this happening in certain conditions on filesystems that do not allow executable files to be run directly (i.e. the execute bit is ignored). Specifically I've seen this on ISO filesystems on CDs, but it can also be set for other types of filesystems.

That's why I usually explicitly invoke the `sh` or `bash` command within the command to work around these issues, i.e. `sh post_unpack.sh` in your case.
