### ISSUE TITLE
makeself not executing program by sh program

### ISSUE THREAD

**Issue by surjit** [megastep/makeself#79]
I have copied binary to /home/ZesleInstall and then below command
makeself --target /home/ZesleInstall ./ZesleInstall ./latest "Zesle Installer" ./latest

when I run ./latest it works fine and when i try sh latest, it does not work
I need to install it by http url -> curl -o latest -L http://example.com/latest && sh latest

what wrong with above and how can i fix it.

**Comment by megastep** [comment]
If your embedded file is not a shell script, then you don't need to use sh to run it.

**Comment by surjit** [comment]
I have binary 
can you correct this makeself --target /home/ZesleInstall ./ZesleInstall ./latest "Zesle Installer" ./latest

**Comment by megastep** [comment]
This command line makes no sense. Are you trying to make a new archive or extract one?

**Comment by surjit** [comment]
new archive that can be installed by below url
curl -o latest -L http://example.com/latest && sh latest

**Comment by megastep** [comment]
I think you are being confused by the name of the binary you are including inside the archive and the archive itself, since they seem to have the same name 'latest'. This is not going to work properly because they will be in the same directory and interfere with each other.

If the binary is at the right place in the directory, you would probably create it with something like this:

```makeself /home/ZesleInstall latest.run "Zesle installer" ./latest```

You will then get a latest.run that you can upload and rename if you want.

**Comment by surjit** [comment]
still not working 

I have binary file that i want to make self extracting so, when curl -o latest -L http://example.com/latest && sh latest 

it starts installation on user server

my goal to do something like https://documentation.cpanel.net/display/ALD/Installation+Guide
cd /home && curl -o latest -L https://securedownloads.cpanel.net/latest && sh latest cpanel does
